version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "yarn.lock" }}
            - node-modules-
      - run: yarn install
      - save_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn build
      - save_cache:
          key: dist-{{ epoch }}
          paths:
            - dist
  deploy-prod:
    docker:
      - image: circleci/node:9.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: node-modules-
      - restore_cache:
          key: dist-
      - run:
          name: Deploy to production
          command: |
            node_modules/.bin/netlify deploy \
                --access-token "${NETLIFY_ACCESS_TOKEN}" \
                --site-id "${NETLIFY_SITE_ID}" \
                --path dist

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master
