version: 2
jobs:
  checkout:
    docker:
      - image: circleci/node:9.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
  lint:
    docker:
      - image: circleci/node:9.4
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: yarn lint
  build:
    docker:
      - image: circleci/node:9.4
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy-prod:
    docker:
      - image: circleci/node:9.4
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - deploy:
          command: |
            node_modules/.bin/netlify deploy \
                --access-token "${NETLIFY_ACCESS_TOKEN}" \
                --site-id "${NETLIFY_SITE_ID}" \
                --path dist

workflows:
  version: 2
  Procedure110-Montauk:
    jobs:
      - checkout
      - lint:
          requires:
            - checkout
      - build:
          requires:
            - checkout
      - deploy-prod:
          requires:
            - lint
            - build
          filters:
            branches:
              only: master
