version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: yarn build
      - save_cache:
          key: dist-{{ epoch }}
          paths:
            - ~/repo/dist

workflows:
  version: 2
  build:
    jobs:
      - build
